# Default values for kor-base.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: 667950714614.dkr.ecr.us-east-2.amazonaws.com/totem-core-explorer-api
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "dev"

fullnameOverride: "dev-totem-core-explorer-api"

containerPort: 3000

service:
  type: NodePort
  port: 80
  targetPort: 3000

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/success-codes: '404'
    alb.ingress.kubernetes.io/group.name: main
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-2:667950714614:certificate/302a21b6-52db-4471-a6e5-b530540345a0
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80},{"HTTPS": 443}]'
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/scheme: internet-facing
    external-dns.alpha.kubernetes.io/ingress-hostname-source: annotation-only

  hosts:
    - host: dev-api.totem.gdn
      paths:
        - path: /
          pathType: Prefix
          backend:
            serviceName: dev-totem-core-explorer-api
            servicePort: 80
  tls: []

resources:
  limits:
    cpu: 100m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80
  scaleDownSeconds: 3

tolerations:
  - key: "dedicated"
    operator: "Equal"
    value: "core"
    effect: "NoSchedule"

env:
  ENV: ""
  
